### ISSUE TITLE
wrong example codes

### ISSUE THREAD

**Issue by krtschmr** [escpos/escpos#14]
```
[29] pry(main)> @printer = Escpos::Printer.new
=> #<Escpos::Printer:0x00007efc2e1bbd78 @data="\e@">
[30] pry(main)> @printer << "Some text"
=> "\e@Some text"
[31] pry(main)> @printer << Escpos::Helpers.big("Big text")
NoMethodError: undefined method `big' for Escpos::Helpers:Module
```

even had to wrap `big` call in brackets, otherwise syntax error. 

Ruby 3.2

**Comment by svoboda-jan** [comment]
Hello, thish might be due to some changes in Ruby 3. The following example works as expected in mentioned version:
```ruby
require "escpos"
@printer = Escpos::Printer.new
@printer << "Text"
@printer << Escpos::Helpers.big("Big text")
pp @printer
# "\e@Text\e!0Big text\e!\x00"
puts RUBY_VERSION
# 2.7.1
```

**Comment by krtschmr** [comment]
considering 3.2 is released, i'm more in favor of fixing it.

**Comment by svoboda-jan** [comment]
Sure, but so far haven't found any incompatibility. Could you try to run the example I posted in console? Thanks.

**Comment by svoboda-jan** [comment]
By console I mean running it without any debugging tools like `pry` or `irb`. Just running a shell command:
`ruby escpos_example.rb` with the posted code. Also there is a workaround that might help you meanwhile we figure it out:

```ruby
escpos_helpers = Class.new { include Escpos::Helpers }.new
@printer << escpos_helpers.big("Big text")
```

**Comment by barhum** [comment]
I believe helpers.encode no longer works on Ruby 3.0 + as setting arguments as encode(data, opts = {}) is no longer allowed
